name = "Hugo - Works"
license = "MIT"
licenselink = "https://github.com/pard68/hugo-works/blob/master/LICENSE.md"
description = "A minimal blog theme. Based off hugo-classic by goodroot. Styled after werc by cat-v."
homepage = "https://www.0x44.pw"
tags = ["minimal", "blog", "personal", "simple", "clean", "starter", "minimalist"]
features = ["blog"]
min_version = "0.0.1"

[author]
  author = "Ian Pringle"
  homepage = "https://www.0x44.pw/"
  repo = "https://github.com/pard68/hugo-works"

[original]
  name = "Kellen Evan Person"
  homepage = "https://goodroot.ca"

